### ISSUE TITLE
Current version of tablesorter is not included

### ISSUE THREAD

**Issue by bplexico** [linjunpop/jquery-tablesorter-rails#5]
Mottie's tablesorter plugin has been updated to version 2.4.1.  Can this gem be updated to include the updated version?

**Comment by linjunpop** [comment]
@plexgit Thank you for mention that. It seems that the tablesorter version 2.4 is a big change. And I use a rake task to copy the css/javascript files to vendor folder, v2.4 had some changes on the file structure, so the rake task is broken now.

I need to spend some time to rewrite the rake task, since it's very ugly.

But I'm a little busy these days, and if you wish, you can do some changes and send a PR, if not, I will do that couple days later

**Comment by semirenko** [comment]
Hi, linjunpop!
Any updates about rake task rewriting?

Thanks in advance!

**Comment by linjunpop** [comment]
@semirenko @plexgit

Hi, Thanks all and I just pushed a branch `tablesorter-2.4.6` to GitHub.

And I will keep this issue open and I wont release a new version until it's approved to be correct.

Please feel free to checkout, if there's anything wrong, please let me know. Thank you. :smile:

**Comment by linjunpop** [comment]
Released v1.1.0
